@token = Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MmIxZjJkZDM1MWE1NTAyYTFmZTgzYzEiLCJuYW1lIjoiZGV2IiwiZW1haWwiOiJkZXZAZ21haWwuY29tIiwicm9sZSI6ImFkbWluIiwiZXhwIjoxNjU1OTIzODI0fQ.AvKxE3xnutBaecyydKdSJYDb7ZudQ2DdwgnclRxce2k

###
GET http://localhost:4000/api/v1/products/all
Content-Type: application/json
Authorization: {{token}}
###
GET http://localhost:4000/api/v1/products?page=1&limit=10
Content-Type: application/json

###
GET http://localhost:4000/api/v1/products/62ab22ab5d2ff9327c7c3e0e
Content-Type: application/json

### CREATE PRODUCT --admin
POST http://localhost:4000/api/v1/admin/products/new
Content-Type: application/json
Authorization: {{token}}

{
    "name": "Samsung",
    "description": "2",
    "price": 7000,
    "cutted_price":400,
    "category":"Smartphone",
    "stock": 25,
    "warranty": 10000,
    "ratings": 0
}

### UPDATE PRODUCT --admin
PUT http://localhost:4000/api/v1/admin/products/62b1f8c13732b0043487d6e7
Content-Type: application/json
Authorization: {{token}}

{
    "name": "Lenovo Ideapad UPDATED",
    "description": "Tes",
    "price": 1,
    "cutted_price":50000,
    "category":"Laptop",
    "stock": 17,
    "warranty": 20000,
    "ratings": 4.5,
    "num_of_reviews": 10
}


### DELETE PRODUCT --admin
DELETE http://localhost:4000/api/v1/admin/products/62b1f8c13732b0043487d6e7
Content-Type: application/json
Authorization: {{token}}

### Create Review
PUT http://localhost:4000/api/v1/product/62b208878143097ae895149d/review
Content-Type: application/json
Authorization: {{token}}

{
    "rating": 3.5,
    "comment": "hhh"
}

### Get Review By Product ID --admin
GET http://localhost:4000/api/v1/admin/reviews?id=62b208878143097ae895149d
Content-Type: application/json
Authorization: {{token}}

### DELETE Review BY ID --admin
DELETE http://localhost:4000/api/v1/admin/review?id=62b208878143097ae895149d
Content-Type: application/json
Authorization: {{token}}

{
    "reviews": [
      {
        "user_id": "62b1f2dd351a5502a1fe83c1",
        "product_id": "62b208878143097ae895149d",
        "fullname": "dev",
        "rating": 4.3,
        "comment": "JJJ"
      }
    ]
}