@token = Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MmFkZTlhMjRmZDJiMjQzZGU2Mjc5YmEiLCJuYW1lIjoiYWRtaW4iLCJlbWFpbCI6ImFkbWluQGdtYWlsLmNvbSIsInJvbGUiOiJhZG1pbiIsImV4cCI6MTY1NTU2ODMwNX0.yyBDDqRtiSL96asbb5155Coi4dTgQgBP_JVmUra9_P4

###
GET http://localhost:4000/api/v1/products/all
Content-Type: application/json
Authorization: {{token}}
###
GET http://localhost:4000/api/v1/products?page=1&limit=10
Content-Type: application/json

###
GET http://localhost:4000/api/v1/products/62ab22ab5d2ff9327c7c3e0e
Content-Type: application/json

###
POST http://localhost:4000/api/v1/admin/products/new
Content-Type: application/json
Authorization: {{token}}

{
    "name": "Samsung",
    "description": "phone terbaik",
    "price": 800000,
    "cutted_price":7000,
    "category":"Smartphone",
    "stock": 25,
    "warranty": 10000,
    "ratings": 4.8,
    "num_of_reviews": 10
}

###
PUT http://localhost:4000/api/v1/admin/products/62ab22ab5d2ff9327c7c3e0e
Content-Type: application/json
Authorization: {{token}}

{
    "name": "Lenovo Ideapad UPDATED",
    "description": "Tes",
    "price": 1,
    "cutted_price":50000,
    "category":"Laptop",
    "stock": 17,
    "warranty": 20000,
    "ratings": 4.5,
    "num_of_reviews": 10
}


###
DELETE http://localhost:4000/api/v1/admin/products/62ab22ab5d2ff9327c7c3e0e
Content-Type: application/json
Authorization: {{token}}

### Create Review
POST http://localhost:4000/api/v1/product/62ab22ab5d2ff9327c7c3e0e/review
Content-Type: application/json
Authorization: {{token}}

{
    "rating": 4.5,
    "comment": "This is a good product"
}

### Get All Review --admin
GET http://localhost:4000/api/v1/admin/reviews
Content-Type: application/json
Authorization: {{token}}