@token = Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MmIxNzI3MGJjNzc5ZTQwYjEzNGYxYzciLCJuYW1lIjoiYWRtaW4iLCJlbWFpbCI6ImFkbWluQGdtYWlsLmNvbSIsInJvbGUiOiJhZG1pbiIsImV4cCI6MTY1NTgzMTAxNX0.nH-BmldJml1Ssek9azev6wjT-rEGr83BxMEZPqmJjfQ

###
GET http://localhost:4000/api/v1/products/all
Content-Type: application/json
Authorization: {{token}}
###
GET http://localhost:4000/api/v1/products?page=1&limit=10
Content-Type: application/json

###
GET http://localhost:4000/api/v1/products/62ab22ab5d2ff9327c7c3e0e
Content-Type: application/json

### CREATE PRODUCT --admin
POST http://localhost:4000/api/v1/admin/products/new
Content-Type: application/json
Authorization: {{token}}

{
    "name": "Samsung",
    "description": "2",
    "price": 7000,
    "cutted_price":400,
    "category":"Smartphone",
    "stock": 25,
    "warranty": 10000,
    "ratings": 0
}

### UPDATE PRODUCT --admin
PUT http://localhost:4000/api/v1/admin/products/62ab22ab5d2ff9327c7c3e0e
Content-Type: application/json
Authorization: {{token}}

{
    "name": "Lenovo Ideapad UPDATED",
    "description": "Tes",
    "price": 1,
    "cutted_price":50000,
    "category":"Laptop",
    "stock": 17,
    "warranty": 20000,
    "ratings": 4.5,
    "num_of_reviews": 10
}


### DELETE PRODUCT --admin
DELETE http://localhost:4000/api/v1/admin/products/62b1e746910dd08715aac212
Content-Type: application/json
Authorization: {{token}}

### Create Review
POST http://localhost:4000/api/v1/product/62b1e76f1669a351da1c9edf/review
Content-Type: application/json
Authorization: {{token}}

{
    "rating": 2.5,
    "comment": "Lumayan!!!"
}

### Get Review By Product ID --admin
GET http://localhost:4000/api/v1/admin/reviews?id=62b1e76f1669a351da1c9edf
Content-Type: application/json
Authorization: {{token}}

### DELETE Review BY ID --admin
DELETE http://localhost:4000/api/v1/admin/review/62b17270bc779e40b134f1c7
Content-Type: application/json
Authorization: {{token}}