@token = Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MmFjM2RlZTMzYjY0MmQ0NWMxYTQzN2MiLCJuYW1lIjoiYWRtaW4iLCJlbWFpbCI6ImFkbWluQGdtYWlsLmNvbSIsInJvbGUiOiJhZG1pbiIsImV4cCI6MTY1NTU0MTg1Nn0.pS-BOiumKpnucoETemHHkM-nSX8NhtbJDgFiDwvwwMw

### GET USER TRANSACTION
GET http://localhost:5000/api/v1/transactions
Content-Type: application/json
Authorization: {{token}}

### GET PRODUCT TRANSACTION
GET http://localhost:5000/api/v1/product/62ab22ab5d2ff9327c7c3e0e/transaction
Content-Type: application/json
Authorization: {{token}}

### Create Transaction
POST http://localhost:5000/api/v1/transaction/new
Content-Type: application/json
Authorization: {{token}}

{
    "product_id": "62ab22ab5d2ff9327c7c3e0e",
    "amount": 50000
}

### Proses Payment
POST http://localhost:5000/api/v1/transaction/notification
Content-Type: application/json
Authorization: {{token}}

